In [14]:
import pyzx as zx 
from graph_loader import load_graph
import networkx as nx
from f2linalg.f2linalg import Mat2
import numpy as np
from pyzx.pauliweb import PauliWeb
from detection_webs import get_detection_webs

In [ ]:
g1 = load_graph("zxgs/borghans_state.zxg")
zx.draw(g1, labels=True)

In [16]:
g1.set_outputs([5,6,7])
pws = get_detection_webs(g1)
for pw in pws:
    zx.draw(g1, labels=True, pauli_web=pw)

[0 0 0 0 0 0 1 1]
{3: 3, 4: 4, 0: 5, 1: 6, 2: 7}
2
Z


In [17]:
g = load_graph("zxgs/xx_stab_choi.zxg")
g.set_inputs([4,5])
g.set_outputs([6,7])
pws = get_detection_webs(g)
for pw in pws:
    zx.draw(g, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
{0: 4, 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 12, 9: 13, 10: 14, 11: 15}
1
X


In [18]:
g2 = load_graph("zxgs/xx_stab.zxg")
g2.set_inputs([4,5])
g2.set_outputs([6,7])
pws = get_detection_webs(g2)
for pw in pws:
    zx.draw(g2, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
{0: 4, 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 12, 9: 13, 10: 14, 11: 15}
1
X


In [19]:
test_g2 = load_graph("zxgs/xxx_detection_graph.zxg")
zx.draw(test_g2, labels=True)


In [20]:
# Actually, what about the back action to our ancilla initialisations?
test_g2.set_inputs([23,21,22])
test_g2.set_outputs([26,14,28])
pws = get_detection_webs(test_g2)
for pw in pws:
    zx.draw(test_g2, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
{6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 0: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 1: 21, 2: 22, 3: 23, 20: 24, 21: 25, 4: 26, 22: 27, 5: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 35, 30: 36, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51}
2
Z
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
{6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 0: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 1: 21, 2: 22, 3: 23, 20: 24, 21: 25, 4: 26, 22: 27, 5: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 35, 30: 36, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51}
2
Z
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [21]:
test_g3 = load_graph("zxgs/xxx_2_detection_graph.zxg")
zx.draw(test_g3, labels=True)

In [22]:
test_g3.set_inputs([11,44,43])
test_g3.set_outputs([65,61,90])
pws = get_detection_webs(test_g3)
for pw in pws:
    zx.draw(test_g3, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 0: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 35, 35: 36, 36: 37, 37: 38, 38: 39, 39: 40, 40: 41, 41: 42, 1: 43, 2: 44, 42: 45, 43: 46, 44: 47, 45: 48, 46: 49, 47: 50, 48: 51, 49: 52, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 59, 57: 60, 3: 61, 58: 62, 59: 63, 60: 64, 4: 65, 61: 66, 62: 67, 63: 68, 64: 69, 65: 70, 66: 71, 67: 72, 68: 73, 69: 74, 70: 75, 71: 76, 72: 77, 73: 78, 74: 79, 75: 80, 76: 81, 77: 82, 78: 83, 79: 84, 80: 85, 81: 86, 82: 87, 83: 88, 84: 89, 5: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98}
2
Z
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 

In [23]:
test_g4 = load_graph("zxgs/star_graph_2_rounds_rg.zxg")
zx.draw(test_g4, labels=True)

In [24]:
test_g4.set_inputs([8,7,6])
test_g4.set_outputs([23,19,17])
pws = get_detection_webs(test_g4)
for pw in pws:
    zx.draw(test_g4, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0]
{0: 6, 1: 7, 2: 8, 6: 9, 7: 10, 8: 11, 9: 12, 10: 13, 11: 14, 12: 15, 13: 16, 3: 17, 14: 18, 4: 19, 15: 20, 16: 21, 17: 22, 5: 23, 18: 24, 19: 25, 20: 26, 21: 27}
1
X
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0]
{0: 6, 1: 7, 2: 8, 6: 9, 7: 10, 8: 11, 9: 12, 10: 13, 11: 14, 12: 15, 13: 16, 3: 17, 14: 18, 4: 19, 15: 20, 16: 21, 17: 22, 5: 23, 18: 24, 19: 25, 20: 26, 21: 27}
2
Z
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1]
{0: 6, 1: 7, 2: 8, 6: 9, 7: 10, 8: 11, 9: 12, 10: 13, 11: 14, 12: 15, 13: 16, 3: 17, 14: 18, 4: 19, 15: 20, 16: 21, 17: 22, 5: 23, 18: 24, 19: 25, 20: 26, 21: 27}
2
Z


In [1]:
test_g5 = load_graph("zxgs/2_rounds_steane_rg.zxg")
zx.draw(test_g5, labels=True)

NameError: name 'load_graph' is not defined

In [ ]:
test_g5.set_inputs([19,20,21,17,16,15,14])
test_g5.set_outputs([65,73,71,62,60,72,67])
pws = get_detection_webs(test_g5)
for pw in pws:
    zx.draw(test_g5, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0]
{0: 14, 1: 15, 2: 16, 3: 17, 14: 18, 4: 19, 5: 20, 6: 21, 15: 22, 16: 23, 17: 24, 18: 25, 19: 26, 20: 27, 21: 28, 22: 29, 23: 30, 24: 31, 25: 32, 26: 33, 27: 34, 28: 35, 29: 36, 30: 37, 31: 38, 32: 39, 33: 40, 34: 41, 35: 42, 36: 43, 37: 44, 38: 45, 39: 46, 40: 47, 41: 48, 42: 49, 43: 50, 44: 51, 45: 52, 46: 53, 47: 54, 48: 55, 49: 56, 50: 57, 51: 58, 52: 59, 7: 60, 53: 61, 8: 62, 54: 63, 55: 64, 9: 65, 56: 66, 10: 67, 57: 68, 58: 69, 59: 70, 11: 71, 12: 72, 13: 73, 60: 74, 61: 75, 62: 76, 63: 77, 64: 78, 65: 79, 66: 80, 67: 81, 68: 82, 69: 83, 70: 84, 71: 85, 72: 86, 73: 87, 74: 88, 75: 89, 76: 90, 77: 91, 78: 92, 79: 93, 80: 94, 81: 95, 82: 96, 83: 97, 84: 98}
1
X


: 

In [29]:
test_g6 = load_graph("zxgs/hadamard_test.zxg")
zx.draw(test_g6, labels=True)

In [30]:
test_g6.set_inputs([0,1])
test_g6.set_outputs([2,3])
pws = get_detection_webs(test_g6)
for pw in pws:
    zx.draw(test_g6, labels=True, pauli_web=pw)

[0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1]
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11}
1
X
